IF NOT EXISTS (SELECT name FROM sys.tables where name = 'DimSite')
	CREATE TABLE [dbo].[DimSite](
	[SiteKey] [int] IDENTITY(1,1) NOT NULL,
	[SiteID] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[SiteURL] [nvarchar](50) NULL,
	[CountryName] [nvarchar](50) NULL,
	[CountryVat] [float] NULL,
	[CountryCode] [nvarchar](2) NULL,
	[CountryEuroZone] [bit],
	[StoreContact] [nvarchar](50) NULL,
	[AddressKey] [int],
	--[AddressLine1] [nvarchar](200) NULL,
	--[AddressLine2] [nvarchar](200) NULL,
	--[Zip] [nvarchar](11) NULL,
	--[City] [nvarchar](50) NULL,
	[CurrencyKey] [int],
	[Phone] [nvarchar](11) NULL,
	[TimeZone] [nvarchar](50) NULL,
	[ServiceCode] [int] NULL, 
	[ServiceType] [nchar](1) NULL,
	[ServiceDescription] [nvarchar] (255) NULL,
	[EffectiveDate] [datetime] NOT NULL,
	[ExpiredDate] [datetime] NULL,
	[IsCurrent] [nvarchar](3) NOT NULL
		) ON [PRIMARY]